import { VehicleType, PaintType, OptionItem, VehicleSize, PricingType } from './types';

// Step 1-1: Vehicle Types
export const VEHICLES: VehicleType[] = [
 {
  id: 'kei',
  name: '軽自動車',
  category: VehicleSize.LIGHT,
  image: 'https://picsum.photos/id/111/300/200',
  prices: {
   solid: 100000,
   metallic: 120000,
   pearl: 140000,
  },
 },
 {
  id: 'compact',
  name: 'コンパクトカー',
  category: VehicleSize.REGULAR,
  image: 'https://picsum.photos/id/133/300/200',
  prices: {
   solid: 120000,
   metallic: 140000,
   pearl: 160000,
  },
 },
 {
  id: 'sedan',
  name: '中型セダン',
  category: VehicleSize.REGULAR,
  image: 'https://picsum.photos/id/183/300/200',
  prices: {
   solid: 140000,
   metallic: 160000,
   pearl: 180000,
  },
 },
 {
  id: 'suv',
  name: 'SUV',
  category: VehicleSize.LARGE,
  image: 'https://picsum.photos/id/296/300/200',
  prices: {
   solid: 160000,
   metallic: 180000,
   pearl: 200000,
  },
 },
 {
  id: 'minivan',
  name: 'ミニバン・大型',
  category: VehicleSize.LARGE,
  image: 'https://picsum.photos/id/291/300/200',
  prices: {
   solid: 200000,
   metallic: 220000,
   pearl: 240000,
  },
 },
 {
  id: 'onebox',
  name: 'ワンボックス',
  category: VehicleSize.LARGE,
  image: 'https://picsum.photos/id/655/300/200',
  prices: {
   solid: 200000,
   metallic: 220000,
   pearl: 240000,
  },
 },
];

// Step 1-2: Paint Menu
export const PAINTS: PaintType[] = [
 {
  id: 'solid',
  name: 'ソリッド (単色)',
  description: 'シンプルで力強い発色。クラシックな印象に。',
  image: 'https://picsum.photos/seed/blue/400/300',
 },
 {
  id: 'metallic',
  name: 'メタリック',
  description: '金属片を含んだ塗料で、キラキラとした輝きを放ちます。',
  image: 'https://picsum.photos/seed/silver/400/300',
 },
 {
  id: 'pearl',
  name: 'パール',
  description: '真珠のような深みのある光沢と高級感を演出します。',
  image: 'https://picsum.photos/seed/pearl/400/300',
 },
];

// Step 2 & 3: Options
export const OPTIONS: OptionItem[] = [
 // --- Prep & Repair ---
 {
  id: 'clear_peel',
  name: 'クリアー剥離',
  description: '劣化したクリア層を剥がして下地を整えます',
  detailDescription: '長年の紫外線や経年劣化により、塗装表面のクリア層が剥がれたり白く濁ったりしている場合に必要な処理です。古いクリア層を丁寧に研磨・除去し、新しい塗装がしっかりと密着する平滑な下地を作ります。この工程を省くと、新しい塗装の仕上がりが悪くなったり、すぐに剥がれてしまう原因となります。',
  category: 'prep',
  pricingType: PricingType.PER_UNIT,
  price: 10000,
  unitLabel: 'パネル',
  image: 'https://picsum.photos/seed/peel/150/150',
 },
 {
  id: 'scratch_repair',
  name: '擦り傷補修',
  description: '車体の擦り傷を補修します',
  detailDescription: 'ボディについた浅い擦り傷から深いガリ傷まで、丁寧に補修します。パテ埋め、研磨、サフェーサー塗布などの工程を経て、傷跡が全く分からないように平滑に仕上げます。全塗装の前にこの下地処理をしっかり行うことで、新車のような美しい仕上がりが実現します。',
  category: 'prep',
  pricingType: PricingType.PER_UNIT,
  price: 10000,
  unitLabel: 'パネル',
  image: 'https://picsum.photos/seed/scratch/150/150',
 },
 {
  id: 'dent_repair',
  name: '凹み補修',
  description: '車体の凹みを補修します',
  detailDescription: 'ドアパンチや接触事故などでできてしまったボディの凹みを修復します。専用のツールを使用して凹みを引き出し、パテで成形して元の形状を復元します。光の反射で歪みが見えないレベルまで精密に仕上げるため、全塗装後の映り込みが非常に美しくなります。',
  category: 'prep',
  pricingType: PricingType.PER_UNIT,
  price: 10000,
  unitLabel: 'パネル',
  image: 'https://picsum.photos/seed/dent/150/150',
 },
 {
  id: 'wrapping_peel',
  name: 'ラッピング剥離',
  description: '既存のラッピングを全て剥がします',
  detailDescription: '現在施工されているカーラッピングフィルムを全て剥がし、糊残りを除去して塗装可能な状態にします。劣化したフィルムは剥がすのが困難な場合がありますが、専用の機材と溶剤を使用してボディを傷めずに綺麗に除去します。',
  category: 'prep',
  pricingType: PricingType.FIXED,
  price: 50000,
  image: 'https://picsum.photos/seed/wrap/150/150',
 },

 // --- Parts Removal ---
 {
  id: 'parts_removal_set',
  name: '外廻り 脱着セット',
  description: 'バンパー、ライト、ドアノブ等の脱着を行い綺麗に仕上げます。',
  detailDescription: '全塗装のクオリティを格段に上げるためのセットオプションです。バンパー、ヘッドライト、テールランプ、ドアノブ、ドアミラー、モール類などを一度取り外してから塗装します。これにより、パーツの際（きわ）までしっかりと塗装が入り込み、マスキング跡が残らない純正のような自然な仕上がりになります。',
  category: 'parts',
  pricingType: PricingType.VARIES_BY_SIZE,
  price: {
   [VehicleSize.LIGHT]: 25000,
   [VehicleSize.REGULAR]: 35000,
   [VehicleSize.LARGE]: 45000,
  },
  image: 'https://picsum.photos/seed/parts/150/150',
 },
 {
  id: 'parts_removal_aero',
  name: 'エアロ脱着追加',
  description: 'エアロパーツ装着車の場合の追加料金',
  detailDescription: '社外エアロパーツや純正オプションのエアロパーツが装着されている場合、それらの脱着には追加の工数がかかります。サイドステップ、フロントリップ、リアスポイラーなどを丁寧に取り外し、単体で塗装してから再度組み付けることで、細部まで完璧な仕上がりを提供します。',
  category: 'parts',
  pricingType: PricingType.FIXED,
  price: 20000,
  image: 'https://picsum.photos/seed/aero/150/150',
 },
 {
  id: 'glass_removal',
  name: 'ガラス脱着セット',
  description: 'ガラスを取り外して塗装します（モール交換含む）',
  detailDescription: 'フロントガラスやリアガラスを取り外して塗装を行う、こだわりのオプションです。ガラスのゴムモール（ウェザーストリップ）の下まで確実に塗装できるため、経年による塗装剥がれのリスクを最小限に抑えられます。また、劣化したモールも新品に交換するため、見た目のリフレッシュ効果も絶大です。',
  category: 'parts',
  pricingType: PricingType.FIXED,
  price: 50000,
  image: 'https://picsum.photos/seed/glass/150/150',
 },

 // --- Painting Options ---
 {
  id: 'door_inner',
  name: 'ドア中塗装',
  description: 'ドアを開けた内側部分も塗装します',
  detailDescription: '通常の外装塗装（ドアを閉めた状態で見える部分）に加え、ドアを開けたときに見えるステップ部分、ピラー、ドアの内側パネルなども塗装します。乗り降りの際に元の色が全く見えなくなるため、元色とは全く違う色に全塗装する場合に特におすすめのオプションです。',
  category: 'special',
  pricingType: PricingType.VARIES_BY_SIZE,
  price: {
   [VehicleSize.LIGHT]: 10000,
   [VehicleSize.REGULAR]: 15000,
   [VehicleSize.LARGE]: 15000,
  },
  unitLabel: 'ドア',
  image: 'https://picsum.photos/seed/door/150/150',
 },
 {
  id: 'two_tone',
  name: '2色塗装',
  description: 'ルーフなどを別の色で塗り分ける場合',
  detailDescription: 'ルーフ（屋根）やドアミラーなどをボディカラーとは異なる色で塗装し、ツートンカラーに仕上げます。人気のホワイト×ブラックルーフや、クラシックなベージュ×ホワイトルーフなど、お好みの組み合わせでオリジナリティあふれる一台を作成できます。',
  category: 'special',
  pricingType: PricingType.FIXED,
  price: 30000,
  image: 'https://picsum.photos/seed/twotone/150/150',
 },
 {
  id: 'matte',
  name: 'マット塗装 (艶消し)',
  description: 'ワイルドでモダンな艶消し仕上げに変更',
  detailDescription: '通常の艶あり塗装ではなく、光沢を抑えたマット（艶消し）仕上げに変更します。ミリタリーテイストやアウトドアスタイル、あるいは高級感のあるフローズンカラーなど、独特の質感と存在感を演出できます。専用のマットクリアーを使用し、耐久性も確保しています。',
  category: 'special',
  pricingType: PricingType.VARIES_BY_SIZE,
  price: {
   [VehicleSize.LIGHT]: 30000,
   [VehicleSize.REGULAR]: 40000,
   [VehicleSize.LARGE]: 50000,
  },
  image: 'https://picsum.photos/seed/matte/150/150',
 },
 {
  id: 'clear_coat',
  name: '高品位クリアーコート',
  description: '通常より厚みと光沢のあるクリアー層を追加',
  detailDescription: '標準のクリアー塗装よりもさらにグレードの高い、高品位なクリアー塗料を使用します。塗膜の厚み（肉持ち感）が増し、濡れたような深い艶が得られます。また、対候性や耐擦り傷性も向上するため、美しい輝きを長期間維持したい方におすすめです。',
  category: 'special',
  pricingType: PricingType.VARIES_BY_SIZE,
  price: {
   [VehicleSize.LIGHT]: 30000,
   [VehicleSize.REGULAR]: 40000,
   [VehicleSize.LARGE]: 50000,
  },
  image: 'https://picsum.photos/seed/clear/150/150',
 },
 {
  id: 'mirror_finish',
  name: '鏡面仕上げ',
  description: '塗装肌を平滑に磨き上げる最高級の仕上げ',
  detailDescription: '塗装後に職人が時間をかけて丁寧に磨き上げ、塗装表面の微細な凹凸（ゆず肌）を極限まで平滑にする処理です。鏡のように景色が映り込む、ショーカーレベルの圧倒的な光沢と透明感を実現します。究極の美しさを求める方のためのプレミアムメニューです。',
  category: 'special',
  pricingType: PricingType.FIXED,
  price: 50000,
  image: 'https://picsum.photos/seed/mirror/150/150',
 },
 {
  id: 'raptor',
  name: 'ラプター塗装',
  description: '傷に強い高耐久ウレタン塗装（バンパー等）',
  detailDescription: 'イギリス製の高耐久ウレタン塗料「ラプターライナー」を使用した塗装です。ザラザラとした独特の質感が特徴で、傷、摩耗、汚れ、紫外線に極めて強い耐性を持ちます。バンパー、フェンダー、グリルなどに施工することで、タフでワイルドなオフロードスタイルを演出できます。',
  category: 'special',
  pricingType: PricingType.FIXED,
  price: 30000,
  image: 'https://picsum.photos/seed/raptor/150/150',
 },

 // --- Coating & Others ---
 {
  id: 'glass_coating',
  name: 'ガラス全面コーティング',
  description: '塗装後のボディを保護し、輝きを持続させます',
  detailDescription: '全塗装で美しくなったボディを、ガラスコーティングの被膜で強力に保護します。汚れが付きにくく落ちやすくなるため、日頃のお手入れが格段に楽になります。また、紫外線や酸性雨から塗装を守り、色あせや劣化を防ぐ効果もあります。',
  category: 'coating',
  pricingType: PricingType.FIXED,
  price: 5000,
  image: 'https://picsum.photos/seed/coating/150/150',
 },
 {
  id: 'headlight_clear',
  name: 'ヘッドランプクリアー塗装',
  description: '黄ばみを除去しクリア塗装で保護 (左右)',
  detailDescription: '経年劣化で黄ばんだり白く曇ってしまったヘッドライトを研磨してクリアな状態に戻し、その上から専用のクリアー塗装を施します。市販のコーティング剤とは異なり、塗装による厚い被膜で保護するため、透明度が長期間（数年単位）持続します。顔つきが引き締まり、車全体の印象が若返ります。',
  category: 'coating',
  pricingType: PricingType.FIXED,
  price: 10000,
  image: 'https://picsum.photos/seed/lamp/150/150',
 },
 {
  id: 'wheel_paint',
  name: 'ホイール塗装',
  description: 'ホイールの色替え (1本〜)',
  detailDescription: '純正ホイールや社外ホイールを、ボディカラーに合わせて塗装したり、マットブラックやガンメタなどでスポーティに仕上げたりできます。ガリ傷の補修と同時に行うことも可能です。足元のカラーチェンジは、車の全体のイメージを大きく変える効果的なカスタムです。',
  category: 'special',
  pricingType: PricingType.PER_UNIT,
  price: 5000,
  unitLabel: '本',
  image: 'https://picsum.photos/seed/wheel/150/150',
 },
];